apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza
  template:
    metadata:
      labels:
        app: pizza
    spec:
      containers:
        - name: pizza
          image: linuxacademycontent/pizza-service:1.14.6
          command: ["nginx"]
          args: ["-g","daemon off;"]
          livenessProbe:
            exec:
              command:
              - cat
              - /var/www/html
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 80
