apiVersion: apps/v1
kind: Deployment
metadata:
  name: candy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candy-ws
  template:
    metadata:
      labels:
        app: candy-ws
    spec:
      containers:
      - image: linuxacademycontent/candy-service:2
        name: candy-ws
